version: '3.8'

services:
  web:
    image: image-frontend.kr.ncr.ntruss.com/nextjs-server
    build: .
    ports:
      - '80:3000'
    # networks:
    #   - webnet

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - web
  #   networks:
  #     - webnet
# networks:
#   webnet:
